datasets:
  test:
    index_type: sga_primer
    target_size: 2100
    templates:
      pbsga41:
        fwd_index: SGA_F01
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga42:
        fwd_index: SGA_F02
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga43:
        fwd_index: SGA_F03
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga44:
        fwd_index: SGA_F04
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga45:
        fwd_index: SGA_F05
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga46:
        fwd_index: SGA_F06
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga47:
        fwd_index: SGA_F07
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga48:
        fwd_index: SGA_F08
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga49:
        fwd_index: SGA_F09
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga50:
        fwd_index: SGA_F10
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga51:
        fwd_index: SGA_F11
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
      pbsga52:
        fwd_index: SGA_F12
        fwd_primer: TTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: ATAGGCTGTACTGTCCATTTATCMGG
