datasets:
  2018-12_UW_H704_M2217:
    index_type: nextera
    target_size: 3000
    templates:
      H704_2150_230_REN_e01:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2150_230_REN_e02:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2150_230_REN_e03:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2150_230_REN_e04:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2150_230_REN_e05:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2150_230_REN_e06:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2150_230_REN_e07:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_2150_230_REN_e08:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N701
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_2150_230_REN_e09:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2150_230_REN_e10:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2150_230_REN_e11:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2150_230_REN_e12:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2150_230_REN_e13:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2150_230_REN_e14:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2150_230_REN_e15:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_2150_230_REN_e16:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N702
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_2150_230_REN_e17:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2150_230_REN_e18:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2150_230_REN_e19:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2150_230_REN_e20:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2150_230_REN_e21:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2150_230_REN_e22:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2150_230_REN_e23:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N703
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_2541_081_REN_e01:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2541_081_REN_e02:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2541_081_REN_e03:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2541_081_REN_e04:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2541_081_REN_e05:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2541_081_REN_e06:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2541_081_REN_e07:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_2541_081_REN_e08:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N708
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_2541_081_REN_e09:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2541_081_REN_e10:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2541_081_REN_e11:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2541_081_REN_e12:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2541_081_REN_e13:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2541_081_REN_e14:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2541_081_REN_e15:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_2541_081_REN_e16:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N709
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_2541_081_REN_e17:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2541_081_REN_e18:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2541_081_REN_e19:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2541_081_REN_e20:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2541_081_REN_e21:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2541_081_REN_e22:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2541_081_REN_e23:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_2541_081_REN_e24:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N710
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_2541_081_REN_e25:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_2541_081_REN_e26:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_2541_081_REN_e27:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_2541_081_REN_e28:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_2541_081_REN_e29:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_2541_081_REN_e30:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_2541_081_REN_e31:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N711
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_3083_030_REN_e01:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_3083_030_REN_e02:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_3083_030_REN_e03:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_3083_030_REN_e04:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_3083_030_REN_e05:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_3083_030_REN_e06:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_3083_030_REN_e07:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_3083_030_REN_e08:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N704
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_3083_030_REN_e09:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_3083_030_REN_e10:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_3083_030_REN_e11:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_3083_030_REN_e12:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_3083_030_REN_e13:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_3083_030_REN_e14:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_3083_030_REN_e15:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_3083_030_REN_e16:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N705
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_3083_030_REN_e17:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_3083_030_REN_e18:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_3083_030_REN_e19:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_3083_030_REN_e20:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_3083_030_REN_e21:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_3083_030_REN_e22:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_3083_030_REN_e23:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_3083_030_REN_e24:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N706
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
      H704_3083_030_REN_e25:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S517
      H704_3083_030_REN_e26:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S502
      H704_3083_030_REN_e27:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S503
      H704_3083_030_REN_e28:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S504
      H704_3083_030_REN_e29:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S505
      H704_3083_030_REN_e30:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S506
      H704_3083_030_REN_e31:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S507
      H704_3083_030_REN_e32:
        Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        N7_Index: N707
        Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
        S5_Index: S508
