datasets:
  2019-08_UW_H704_HHV8_IRF3_M4512:
    index_type: sga_primer
    templates:
      CR18d7_6_BACH2_1:
        fwd_index: SGA_F07
        fwd_primer: TCGTCGGCAGCGTCTGGGAAAATGTTAGTTAATTTTGGGATT
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGATTTACTCCACACCACACAACTTAC
      CR18d7_6_BACH2_1_1ul:
        fwd_index: SGA_F11
        fwd_primer: TCGTCGGCAGCGTCTGGGAAAATGTTAGTTAATTTTGGGATT
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGATTTACTCCACACCACACAACTTAC
      CR18d7_6_BACH2_2:
        fwd_index: SGA_F08
        fwd_primer: TCGTCGGCAGCGTCTGGGAAAATGTTAGTTAATTTTGGGATT
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGATTTACTCCACACCACACAACTTAC
      CR18d7_6_BACH2_2_1ul:
        fwd_index: SGA_F12
        fwd_primer: TCGTCGGCAGCGTCTGGGAAAATGTTAGTTAATTTTGGGATT
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGATTTACTCCACACCACACAACTTAC
      CR18d7_6_BACH2_3:
        fwd_index: SGA_F09
        fwd_primer: TCGTCGGCAGCGTCTGGGAAAATGTTAGTTAATTTTGGGATT
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGATTTACTCCACACCACACAACTTAC
      CR18d7_6_BACH2_4:
        fwd_index: SGA_F10
        fwd_primer: TCGTCGGCAGCGTCTGGGAAAATGTTAGTTAATTTTGGGATT
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGATTTACTCCACACCACACAACTTAC
      H704_1225_310_REN_pe01:
        fwd_index: SGA_F01
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe02:
        fwd_index: SGA_F02
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe03:
        fwd_index: SGA_F03
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe04:
        fwd_index: SGA_F04
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe05:
        fwd_index: SGA_F05
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe06:
        fwd_index: SGA_F06
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe07:
        fwd_index: SGA_F07
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe08:
        fwd_index: SGA_F11
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe09:
        fwd_index: SGA_F12
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe10:
        fwd_index: SGA_F01
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe11:
        fwd_index: SGA_F02
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe12:
        fwd_index: SGA_F03
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe13:
        fwd_index: SGA_F04
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe14:
        fwd_index: SGA_F05
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe15:
        fwd_index: SGA_F06
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe16:
        fwd_index: SGA_F07
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe17:
        fwd_index: SGA_F11
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_1225_310_REN_pe18:
        fwd_index: SGA_F12
        fwd_primer: TCGTCGGCAGCGTCGATCAAGCTTTAGGCATCTCCT
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGGTACCTGAGGTCTGACTGGRAAAC
      H704_2150_230_GP_pe01:
        fwd_index: SGA_F01
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe02:
        fwd_index: SGA_F02
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe03:
        fwd_index: SGA_F03
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe04:
        fwd_index: SGA_F04
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe05:
        fwd_index: SGA_F05
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe06:
        fwd_index: SGA_F06
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe07:
        fwd_index: SGA_F07
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe08:
        fwd_index: SGA_F08
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe09:
        fwd_index: SGA_F09
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe10:
        fwd_index: SGA_F10
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe11:
        fwd_index: SGA_F11
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe12:
        fwd_index: SGA_F12
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R01
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe14:
        fwd_index: SGA_F01
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe15:
        fwd_index: SGA_F02
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe16:
        fwd_index: SGA_F03
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe17:
        fwd_index: SGA_F04
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe19:
        fwd_index: SGA_F05
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe22:
        fwd_index: SGA_F06
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe24:
        fwd_index: SGA_F07
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe25:
        fwd_index: SGA_F08
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe26:
        fwd_index: SGA_F09
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe27:
        fwd_index: SGA_F10
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe30:
        fwd_index: SGA_F11
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      H704_2150_230_GP_pe31:
        fwd_index: SGA_F12
        fwd_primer: TCGGCAGCGTCTTGACTAGCGGAGGCTAGAAGGAGA
        rev_index: SGA_R02
        rev_primer: GTCTCGTGGGCTCGGATAGGCTGTACTGTCCATTTATCMGG
      IRF3_17014_wk7_env_p:
        fwd_index: SGA_F08
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17014_wk7_gag_p:
        fwd_index: SGA_F04
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17016_wk7_env_p:
        fwd_index: SGA_F06
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17016_wk7_gag_p:
        fwd_index: SGA_F02
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17022_wk7_env_p:
        fwd_index: SGA_F05
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17022_wk7_gag_p:
        fwd_index: SGA_F01
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17026_wk7_env_p:
        fwd_index: SGA_F05
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17026_wk7_gag_p:
        fwd_index: SGA_F12
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17027_wk7_env_p:
        fwd_index: SGA_F03
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17027_wk7_gag_p:
        fwd_index: SGA_F10
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17030_wk7_env_p:
        fwd_index: SGA_F02
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17030_wk7_gag_p:
        fwd_index: SGA_F09
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17032_wk7_env_p:
        fwd_index: SGA_F04
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17032_wk7_gag_p:
        fwd_index: SGA_F11
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17037_wk7_env_p:
        fwd_index: SGA_F07
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17037_wk7_gag_p:
        fwd_index: SGA_F03
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R03
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
      IRF3_17043_wk7_env_p:
        fwd_index: SGA_F06
        fwd_primer: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATAACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
      IRF3_17043_wk7_gag_p:
        fwd_index: SGA_F01
        fwd_primer: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
        rev_index: SGA_R04
        rev_primer: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
